"""SQLite → PostgreSQL 迁移工具（P01）。

纯函数集合：把 SQLite 的表结构与类型映射为 PostgreSQL DDL。
被 ``scripts/migrate_sqlite_to_postgres.py`` 与单元测试共用。
"""

from __future__ import annotations

import sqlite3
from typing import Any

# Alembic 管理的多租户核心表：这些表由 0001 迁移创建，数据迁移只拷数据
ALEMBIC_MANAGED_TABLES = {"accounts", "risk_events", "alert_records"}

# SQLite 类型 → PostgreSQL 类型映射（SQLite 仅五种存储类）
TYPE_MAP: dict[str, str] = {
    "INTEGER": "INTEGER",
    "REAL": "DOUBLE PRECISION",
    "TEXT": "TEXT",
    "BLOB": "BYTEA",
    "DATETIME": "TIMESTAMP",
    "DATE": "DATE",
    "BOOLEAN": "BOOLEAN",
}


def sqlite_type_to_pg(
    decl_type: str,
    *,
    primary_key: bool = False,
    autoincrement: bool = False,
) -> str:
    """把 SQLite 列类型映射为 PostgreSQL 类型。"""
    base = (decl_type or "TEXT").upper()
    if base.startswith("VARCHAR"):
        return base
    pg_type = TYPE_MAP.get(base, "TEXT")
    if primary_key and autoincrement and pg_type == "INTEGER":
        return "INTEGER GENERATED BY DEFAULT AS IDENTITY"
    return pg_type


def sqlite_table_info(conn: sqlite3.Connection, table: str) -> list[dict[str, Any]]:
    """读取 SQLite 表的列定义（PRAGMA table_info）。"""
    rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
    return [dict(zip(("cid", "name", "type", "notnull", "dflt_value", "pk"), r)) for r in rows]


def generate_pg_ddl(table: str, columns: list[dict[str, Any]]) -> str:
    """根据 SQLite 列定义生成 PostgreSQL CREATE TABLE 语句。"""
    col_defs = []
    for col in columns:
        pg_type = sqlite_type_to_pg(
            col["type"],
            primary_key=bool(col["pk"]),
            autoincrement=col.get("autoincrement", False),
        )
        parts = [f'"{col["name"]}" {pg_type}']
        if col["pk"]:
            parts.append("PRIMARY KEY")
        if col["notnull"] and not col["pk"]:
            parts.append("NOT NULL")
        if col["dflt_value"] is not None:
            default = str(col["dflt_value"])
            # SQLite 默认值字面量直接透传（如 1.0 / 'pending' / (datetime('now'))）
            if not default.startswith("("):
                default = f"({default})"
            parts.append(f"DEFAULT {default}")
        col_defs.append(" ".join(parts))
    return f'CREATE TABLE IF NOT EXISTS "{table}" (\n  ' + ",\n  ".join(col_defs) + "\n)"


def list_tables(conn: sqlite3.Connection) -> list[str]:
    """列出 SQLite 中的业务表（排除 sqlite_ 内部表）。"""
    rows = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
    ).fetchall()
    return [r[0] for r in rows]
