"""P01: SQLite → PostgreSQL 多租户迁移测试。

覆盖：
- Alembic 0001 迁移在 SQLite 上执行后，accounts/risk_events/alert_records
  表结构、account_id 外键列、3 个索引均正确（PG 实机验证留待有 PG 的环境）。
- db.py 的 DATABASE_URL 双 DB 切换逻辑。
- sqlite_to_pg 的类型映射与 DDL 生成纯函数。
"""

import sqlite3
from pathlib import Path

import pytest
from sqlalchemy import create_engine, inspect

from whyfxpg.core.db import (
    DEFAULT_DB_PATH,
    get_database_url,
    is_postgres_url,
)
from whyfxpg.migrations.sqlite_to_pg import (
    generate_pg_ddl,
    list_tables,
    sqlite_table_info,
    sqlite_type_to_pg,
)

PROJECT_ROOT = Path(__file__).resolve().parents[2]


# ──────────────────────────────────────────────────────────────
# Alembic 0001 迁移验证（SQLite 端）
# ──────────────────────────────────────────────────────────────


def _run_alembic_upgrade(db_path: Path) -> None:
    from alembic.config import Config

    from alembic import command

    cfg = Config(str(PROJECT_ROOT / "alembic.ini"))
    cfg.set_main_option("sqlalchemy.url", f"sqlite:///{db_path}")
    command.upgrade(cfg, "head")


def test_alembic_0001_creates_multitenancy_schema(tmp_path: Path) -> None:
    """0001 迁移在空库上创建 accounts + 租户列 + 索引。"""
    db = tmp_path / "p01.db"
    _run_alembic_upgrade(db)

    engine = create_engine(f"sqlite:///{db}")
    insp = inspect(engine)

    # accounts 表（AC-2）
    assert "accounts" in insp.get_table_names()
    acct_cols = {c["name"] for c in insp.get_columns("accounts")}
    assert acct_cols == {
        "id", "company_name", "plan_type", "api_key_hash",
        "api_key_prefix", "monthly_quota", "created_at", "status",
    }

    # risk_events 加 account_id 外键 + created_at（AC-3）
    re_cols = {c["name"] for c in insp.get_columns("risk_events")}
    assert "account_id" in re_cols
    assert "created_at" in re_cols

    # alert_records 加 account_id 外键（AC-4）
    al_cols = {c["name"] for c in insp.get_columns("alert_records")}
    assert "account_id" in al_cols

    # 3 个索引（AC-5）
    indexes = {i["name"] for i in insp.get_indexes("risk_events")}
    assert {
        "idx_risk_events_account",
        "idx_risk_events_manufacturer",
        "idx_risk_events_created",
    } <= indexes
    engine.dispose()


def test_alembic_0001_downgrade_removes_tenant_columns(tmp_path: Path) -> None:
    """downgrade 应删除 account_id/索引/accounts 表。"""
    from alembic.config import Config

    from alembic import command

    db = tmp_path / "p01_down.db"
    cfg = Config(str(PROJECT_ROOT / "alembic.ini"))
    cfg.set_main_option("sqlalchemy.url", f"sqlite:///{db}")
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")

    engine = create_engine(f"sqlite:///{db}")
    insp = inspect(engine)
    assert "accounts" not in insp.get_table_names()
    re_cols = {c["name"] for c in insp.get_columns("risk_events")}
    assert "account_id" not in re_cols
    engine.dispose()


# ──────────────────────────────────────────────────────────────
# db.py DATABASE_URL 双 DB 切换（AC-7）
# ──────────────────────────────────────────────────────────────


def test_get_database_url_defaults_to_sqlite(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.delenv("DATABASE_URL", raising=False)
    assert get_database_url() == str(DEFAULT_DB_PATH)


def test_get_database_url_reads_postgres_env(monkeypatch: pytest.MonkeyPatch) -> None:
    url = "postgresql://user:pass@db:5432/whyfxpg"
    monkeypatch.setenv("DATABASE_URL", url)
    assert get_database_url() == url


@pytest.mark.parametrize(
    ("url", "expected"),
    [
        ("postgresql://u:p@h/db", True),
        ("postgres://u:p@h/db", True),
        ("sqlite:///x.db", False),
        ("/plain/path.db", False),
        ("", False),
    ],
)
def test_is_postgres_url(url: str, expected: bool) -> None:
    assert is_postgres_url(url) is expected


# ──────────────────────────────────────────────────────────────
# sqlite_to_pg 纯函数
# ──────────────────────────────────────────────────────────────


@pytest.mark.parametrize(
    ("decl_type", "kwargs", "expected"),
    [
        ("INTEGER", {}, "INTEGER"),
        ("INTEGER", {"primary_key": True, "autoincrement": True},
         "INTEGER GENERATED BY DEFAULT AS IDENTITY"),
        ("REAL", {}, "DOUBLE PRECISION"),
        ("TEXT", {}, "TEXT"),
        ("BLOB", {}, "BYTEA"),
        ("DATETIME", {}, "TIMESTAMP"),
        ("DATE", {}, "DATE"),
        ("VARCHAR(10)", {}, "VARCHAR(10)"),
        ("UNKNOWN_TYPE", {}, "TEXT"),
        ("", {}, "TEXT"),
    ],
)
def test_sqlite_type_to_pg(decl_type: str, kwargs: dict, expected: str) -> None:
    assert sqlite_type_to_pg(decl_type, **kwargs) == expected


def test_generate_pg_ddl_contains_columns_and_pk() -> None:
    columns = [
        {"cid": 0, "name": "log_id", "type": "INTEGER", "notnull": 1,
         "dflt_value": None, "pk": 1, "autoincrement": True},
        {"cid": 1, "name": "source_id", "type": "TEXT", "notnull": 0,
         "dflt_value": None, "pk": 0},
        {"cid": 2, "name": "status", "type": "TEXT", "notnull": 0,
         "dflt_value": "'pending'", "pk": 0},
    ]
    ddl = generate_pg_ddl("crawl_logs", columns)
    assert "CREATE TABLE IF NOT EXISTS \"crawl_logs\"" in ddl
    assert '"log_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' in ddl
    assert '"source_id" TEXT' in ddl
    assert "DEFAULT ('pending')" in ddl


def test_list_tables_excludes_sqlite_internal() -> None:
    conn = sqlite3.connect(":memory:")
    conn.execute("CREATE TABLE business (id INTEGER PRIMARY KEY)")
    conn.execute("CREATE TABLE other_business (id INTEGER PRIMARY KEY)")
    tables = list_tables(conn)
    assert tables == ["business", "other_business"]
    assert sqlite_table_info(conn, "business")[0]["name"] == "id"
    conn.close()
